#! /bin/sh

# easy(1): interact with HTTP servers and REST services
#
# Yves Arrouye

# Set variables that we rely upon

me=`basename $0`
: ${TMPDIR:=/tmp}

# Setup default behaviors. Those are setup by setting variables rather than
# options.
#
# If invoked as rest(1), use baked and cooked modes by default and assume
# one wants JSON.

case "$me" in
    rest)
	default_content=json
	default_baked=1
	default_cooked=-1
	;;
    *)
	default_baked=0
	default_cooked=0
	;;
esac

# HTTP methods that we support

easy_methods="DELETE HEAD GET OPTIONS PATCH POST PUT TRACE"

# Print usage and help too if needed, then exit

usage() {
    if [ "$1" -eq 0 ]
    then
        u=U
    else
        u=u
        exec >&2
    fi
    echo $u"sage: $me [--help] [-P | --print [-s] [-p prefix] [no]env,[no]func,all] [--cmd file | --script file] [--no-env] [--no-extras] [-j, --json | -f, --form | -a, --as-is ] [-B, --baked] [-W, --wet] [-C, --cooked] [-R, --raw] [-E, --endpoint endpoint] [-q, --query query] [-O, --override] [-V] method resource [data] [curlopt ...]"
    if [ "$1" -eq 0 ]
    then
        cat <<EOF

       --help                   Show this message
       -P | --print [opts] what Print commands to set env or define HTTP functions
       --cmd file | --script file  Print the curl(1) command to file or generate a script
       --no-env                 Do not use environment variables
       --no-extras              Do not add extra behavior not explicitly asked for
       -j, --json               Send and receive JSON data
       -f, --form               Send and receive form data
       -a, --as-is              Send and receive data without modifications
       -B, --baked              Bake data from command line
       -W, --wet	        Do not bake data from command line
       -C, --cooked             Cook response contents
       -R, --raw	        Do not cook response contents
       -E, --endpoint endpoint    Specifies an endpoint (overrides \$EASYENDPOINT)
       -q, --query query        Include the query with the path
       -O, --override           Override POST with the chosen method
       -V                       Create needed data using an editor if possible
       resource                 Resource to operate on
       data                     Data for methods taking data as input
       curlopt ...	        Options for curl(1) in addition to \$RESCURLTOPTS
EOF
    fi

    exit $1
}

# Encode a string in URL encoded format.

urlencode() {
  echo "$*" | sed 's/%/%25/g;s/\[/%5B/g;s/\]/%5D/g;s/|/%7C/g;s/\$/%24/g;s/&/%26/g;s/+/%2B/g;s/,/%2C/g;s/:/%3A/g;s/;/%3B/g;s/=/%3D/g;s/?/%3F/g;s/@/%40/g;s/ /%20/g;s/#/%23/g;s/{/%7B/g;s/}/%7D/g;s/\\/%5C/g;s/\^/%5E/g;s/~/%7E/g;s/`/%60/g'
}

# Escape double quotes in a string.

quotestr() {
    echo ${1+"$@"} | sed 's/"/\\\"/g'
}

# Quote arguments if needed so that they can be passed without being
# split. If the arguments will be in quotes then quote accordingly.
#
# Note: It is assumed that IFS will be made of space, tab and newline.

quote() {
    if [ "$1" = "--in-quotes" ]
    then 
        quote="'"'"'"'"
        shift
    else
	quote="'"
    fi
    qargs=
    for a
    do
	if echo $a | grep -q "[ 	&\"'\
]"
	then
	    q=$quote`echo $a | sed "s/'/'\"'\"/g"`$quote
	    qargs="$qargs $q"
	else
	    if [ -z "$a" ]
	    then
		qargs="$qargs '$a'"
	    else
		qargs="$qargs $a"
	    fi
	fi
    done
    echo "$qargs" | sed 's/^ //'
}

# Call curl(1), cooking results as appropriate. Also prints the curl
# invokation if needed.

callcurl() {
    if [ $cooked -gt 0 ]
    then
	hdrfile=`mktemp -t $me`
	contentfile=`mktemp -t $me`
	trap "rm -f $hdrfile $contentfile" 0 1 2 3 4 5 6 7 8 15

	curl ${1+"$@"} -D $hdrfile -o $contentfile
	res=$?

    	if [ "0$cooked" -gt 1 ]
	then
	    prettyarg=-C
	fi
	if [ -f $hdrfile ]
	then
	    grep -v '^Transfer-Encoding:' $hdrfile | pretty $prettyarg 2>/dev/null
	    echo
	    type="`sed -n 's/^Content-Type:[ 	]*\([^;]*\).*$/\1/p' $hdrfile | tr -d '[\012\015]'`"
	fi
	if [ -f "$contentfile" ]
	then
	    if [ -z "$type" ]
	    then
	        type="`mime -qEC $contentfile 2>/dev/null`"
	    fi
	    pretty $prettyarg $contentfile 2>/dev/null
	fi
	rm -f $hdrfile $contentfile
    else
        curl ${1+"$@"}
	res=$?
    fi
    if [ -n "$printfile" ]
    then
	if [ "$printfile" != "-" ]
	then
	    if ! exec >$printfile
	    then
		exit "$me: could not write to $printfile"
	    fi
	fi
	if [ -n "$printscript" ]
	then
	    for s in /bin/sh /bin/ksh $SHELL
	    do
	 	if [ -x $s ]
		then
		    shell=$s
		    break
		fi
	    done
	    if [ -z "$shell" ]
	    then
		shell=/bin/sh		# Even if it does not exist
	    fi
	    # Generate a script that works equally well on the command
	    # line as in a file.
	    echo "#! $shell"
	    if [ -z "$printminimalscript" ]
	    then
	        which=`which which`
	        cat <<EOF
pretty() {
    _pretty=\`$which pretty 2>/dev/null\`
    if test -n "\$_pretty"; then
	\$_pretty "\$@"
    else
	if test "\$1" = -C; then shift; fi
        cat "\$@"
    fi
}
EOF
	    fi
	    cat <<EOF
trap 'rm -f $datafile' 0 1 2 3 4 5 6 7 8 15
EOF
	    if [ -n "$datafile" ]
	    then
	        echo "cat >$datafile <<EOF"
	        cat $datafile
	        echo "EOF"
	    fi
	fi
	if [ -z "$printminimalscript" -a -n "$cooked" ]
	then
	    endcurlcmd="\\"
	fi
	quote curl ${1+"$@"} $endcurlcmd
	if [ -z "$printminimalscript" -a -n "$cooked" ]
	then
	     echo "    | pretty $prettyarg"
	fi
	echo "rm -f $datafile"
    fi

    return $res
}

# Prepare the curl invokation command line appropriate for the method.
# Bakes arguments if needed, gathers data and edit it through an editor
# if appropriate.

call() {
    method=$1
    shift
    resource=$1
    shift

    proto=`echo $EASYENDPOINT | sed -e 's,:.*,,'`
    host=`echo $EASYENDPOINT | sed -e 's,^[a-z]*://\(.*\),\1,' -e 's,/.*,,'`
    hostdir=`echo $host | sed -e 's,:, ,g'`

    urlbase=`echo $EASYENDPOINT | sed 's,/$,,'`

    format=$content

    datafile=

    takesdata=
    dataopt=--data-ascii	# We do our own encoding

    datafileprefix=@

    case "$method" in
	TRACE)
	    xopt="-X $method"
	    takesdata=yes
	    ;;
 	POST)
	    takesdata=yes
	    ;;
 	PUT)
	    dataopt=-T
	    datafileprefix=
	    takesdata=yes
	    ;;
	GET)
	    if [ -z "$query" ]
	    then
		format=raw
		opt=-G
	    else
		xopt="-X $method"
	    fi
	    takesdata=yes
	    ;;
	HEAD)
	    opt=-I
	    raw=1
	    ;;
	*)
	    xopt="-X $method"
	    ;;
    esac

    if [ -n "$takesdata" ]
    then
	nodatagiven=
	if [ "0$baked" -ne 0 ]
	then
	    data=""
	    queryargs=""
	    if [ "$format" = json ]
	    then
		datastart="{"
		dataend="}"
		datasep=","
	    else
		datastart=
		dataend=
		datasep="&"
	    fi
	    for arg
	    do
		assign='='
		case "$arg" in
		    [^-]*)
			case "$arg" in
			    *=*)
				key=`echo $arg | sed -E 's/^([^:=]+):?=.*/\1/'`
				val=`echo $arg | sed -E 's/^[^:=]+:?=(.*)/\1/'`
				literal=`echo $arg | sed -nE 's/^[^:=]+:=(.*)/\1/p'`
				;;
			    *)
				key="$arg"
				val=
				if [ "$format" = json ]
				then
				    literal=null
				else
				    literal=
				    assign=''
				fi
				;;
			esac

			if [ -z "$data" ]
			then
			    data="$datastart"
			else
			    data="$data$datasep"
			fi
	    	        if [ "$format" = json ]
			then
			    data="$data"'"'"`quotestr $key`"'"'":"
			    if [ -n "$literal" ]
			    then
				data="$data$literal"
			    else
				data="$data"'"'"`quotestr $val`"'"'
			    fi
			else
			    data="$data`urlencode $key`$assign"
			    if [ -n "$literal" ]
			    then
				data="$data$val"
			    else
				data="$data`urlencode $val`"
			    fi
			fi
			shift
			;;
		    *)
			break
			;;
		esac
	    done
	    if [ -n "$data" ]
	    then
		data="$data$dataend"
	    fi
	else
	    case "$1" in
		-)
		    data="@-"
		    shift
		    ;;
		-*)
		    nodatagiven=1
		    ;;
		*)
		    data="$1"
		    shift
		    ;;
	    esac
	fi

	if [ -n "$useeditor" ]
	then
	    if [ -n "$nodatagiven" -o -z "$data" ]
	    then
		nodata=1
	    fi
	    if [ "$useeditor" == "yesyes" -o -n "nodata" ]
	    then
		editor=`(exec 2>/dev/null; which "$VISUAL" || which "$EDITOR" \
                           || which vim || which vi) | tail -n 1`
		if [ -n "$editor" ]
		then
		    tmpfile=`mktemp -t $me`
		    trap "rm -f $tmpfile" 0 1 2 3 4 5 6 7 8 15
		    if [ -n "$nodata" ]
		    then
			if [ ! -t 0 ]
			then
			    cat >$tmpfile
			fi
		    else
			echo "$data" >$tmpfile
		    fi
		    (exec </dev/tty; "$editor" $tmpfile)
		    data=`cat $tmpfile`
		    rm -f $tmpfile
		fi
	    fi
	fi
    fi

    if [ -n "$httpoverride" ]
    then
	httpoverride="X-HTTP-Override: $method"
	method=POST
    fi

    if [ "$content" = json ]
    then
	contenthdr="Content-Type: application/json; charset=utf-8"
	accepthdr="Accept: application/json; charset=utf-8"
    fi

    if [ -n "$dataopt" ]
    then
        datafile=`mktemp -t $me`
        echo "$data" >$datafile
        data="$datafileprefix$datafile"
    fi

    callcurl $mycurlopts $opt $dataopt $data \
	$xopt -H "$httpoverride" -H "$contenthdr" -H "$accepthdr" \
        $EASYCURLOPTS ${1+"$@"} $urlbase$resource$query
    res=$?

    rm -f $datafile

    return $?
}

# Parse all command line arguments appropriately and either print shell
# commands if requested, or proceed to invoke call in order to do the
# the proper invokation of curl.

takeiteasy() {
    while [ $# -ne 0 ]
    do
	donotquotearg=
	firstquotearg=
	case "$1" in
	    -[^-]*)
		for l in `echo $1 | sed -e 's/^-//' -e 's/\(.\)/\1 /g'`
		do
		    curlopt=
		    case "$l" in
			j)
			    content=json
			    ;;
			f)
			    content=form
			    ;;
			a)
			    content=asis
			    ;;
			B)
			    baked=1
			    ;;
			W)
			    baked=0
			    ;;
			c)
			    default_cooked=-1
			    ;;
			C)
			    cooked=`expr 0$cooked + 1`
			    ;;
			R)
			    cooked=0
			    ;;
			P)
			    donotquotearg=1
			    printselfcontained=1
			    printshell=all
			    printall=1
			    ;;
	    		E)
			    test $# -gt 1 || usage 1
			    donotquotearg=1
			    shift
			    EASYENDPOINT=$1
			    ;;
			q)
			    test $# -gt 1 || usage 1
			    firstquotearg="$1"
			    shift
			    query="?$1"
			    ;;
			O)
			    httpoverride=1
			    ;;
			V)
			    case "$useeditor" in
				yes)
				    useeditor="${useeditor}yes"
				    ;;
				"")
				    useeditor=1
				    ;;
			    esac
			    ;;
			*)
			    if [ "$1" != "-$l" ]
			    then
				usage 1     # Our options, unknown letter
			    else
				curlopt=1
				break       # cURL option
			    fi
			    ;;
		    esac
		done
		if [ -n "$curlopt" ]
		then
		    donotquotearg=1
		    break
		fi
		;;
	    --help)
		usage 0
		;;
	    --cmd|--script)
		test $# -gt 1 || usage 1
		firstquotearg="$1"
		if [ "$1" = "--script" ]
		then
		    printscript=1
		    printminimalscript=1
		fi
		shift
		printfile=$1
		;;
	    --print)
		shift
		donotquotearg=1
		while [ $# -gt 0 ]
		do
		    case "$1" in
			-[^-]*)
			    for l in `echo $1 | sed -e 's/^-//' -e 's/\(.\)/\1 /g'`
			    do
				case "$l" in
				    s)
					printselfcontained=1
					;;
				    p)
					test $# -gt 1 || usage 1
					shift
					printprefix="$1"
					;;
				    *)
					usage 1
					;;
				esac
			    done
			    ;;
			*)
			    break
			    ;;
		    esac
		    shift
		done
		printshell=${1-all}
		for f in `echo $printshell | sed 's/,/ /g'`
		do
		    case "$f" in
			env)
			    ;;
			noenv)
			    noprintenv=1
			    ;;
			func)
			    ;;
			nofunc)
			    noprintshellcmd=1
			    ;;
			all)
			    printall=1
			    ;;
			*)
			    usage 5
			    ;;
		    esac
		done
		;;
	    --no-env)
		noenv=1
		;;
	    --no-extras)
		clean=1
		;;
	    --json)
		content=json
		;;
	    --form)
		content=form
		;;
	    --as-is)
		content=asis
		;;
	    --baked)
		baked=1
		;;
	    --wet)
		baked=0
		;;
	    --cooked)
		cooked=`expr 0$cooked + 1`
		;;
	    --raw)
		cooked=0
		;;
	    --endpoint)
		test $# -gt 1 || usage 1
		donotquotearg=1
		shift
		EASYENDPOINT=$1
		;;
	    --override)
		httpoverride=1
		;;
	    --query)
		test $# -gt 1 || usage 1
		firstquotearg="$1"
		shift
		query="?$1"
		;;
	    -*)
		break
		;;
	    *)
		if [ -z "$method" ]
		then
		    method=$1
		    if [ -n "$printshellcmd" ]
		    then
			shift
			break
		    fi
		else
		    break
		fi
		;;
	esac
	if [ -z "$donotquotearg" ]
	then
	    if [ -n "$firstquotearg" ]
	    then
		quotedarg=`quote "$firstquotearg"`
		quotedargs="$quotedargs $quotedarg"
	    fi
            quotedarg=`quote "$1"`
	    quotedargs="$quotedargs $quotedarg"
	fi
	shift
    done

    : ${content:=$default_content}
    : ${baked:=$default_baked}
    if [ $default_cooked -lt 0 ]
    then
	if [ -t 1 ]
	then
	    default_cooked=1
	else
	    default_cooked=0
	fi
    fi
    : ${cooked:=$default_cooked}

    if [ -n "$noenv" ]
    then
	unset EASYENDPOINTS
	unset EASYCURLOPTS
    fi
    if [ -z "$clean" ]
    then
	mycurlopts=-LsS
    fi

    if [ -n "$printshell" ]
    then
    	# Process the --print arguments in the order we have seen then

	if [ -n "$printselfcontained" ]
	then
	    allargs=${printall:+func}
	else
	    if [ -n "$EASYENDPOINT" ]
	    then
		env=env,
	    fi
	    allargs=${printall:+${env}func,config}
	fi

	printargs=`echo $printshell | sed "s/all/$allargs/"`
	for f in `echo $printargs | sed 's/,/ /g'`
	do
	    case "$f" in
		env)
		    if [ -z "$noprintenv" ]
		    then
			case "${SHELL:-/bin/sh}" in
			    csh|*/csh*|tcsh|*/tcsh*)
				export="setenv"
				exporteq=" "
				;;
			    *)
				export="export"
				exporteq="="
				;;
			esac
			echo "$export EASYENDPOINT$exporteq`quote $EASYENDPOINT`;"
		    fi
		    ;;
		func)
		    if [ -z "$noprintshellcmd" ]
		    then
			print_methods=${method:-$easy_methods}
			case "${SHELL:-/bin/sh}" in
			    csh|*/csh*|tcsh|*/tcsh*)
				csh=1
				quoteforsh=--in-quotes
				;;
			esac
			if [ -n "$printselfcontained" ]
			then
			    test -n "$EASYENDPOINT" && endpointarg=" --endpoint `quote $quoteforsh $EASYENDPOINT`"
			    test -n "$EASYCURLOPTS" && easycurloptsargs=" `quote $quoteforsh $EASYCURLOPTS`"
			fi
			if [ -n "$printconfig" ]
			then
			    :
			    shift $#
			else
    			    args=`quote $quoteforsh ${1+"$@"}`
			    if [ -n "$printselfcontained" ]
			    then
		     		easyargs=" --no-env$easyargs$endpointarg"
			    fi
			fi
			if [ -n "$args" ]
			then
			    args=" $args"
			fi
			if [ -n "$csh" ]
			then
			    if [ -n "$args" ]
			    then
				aliasargs=' \!*'
			    fi
			    for method in $print_methods
			    do
				cat <<EOF
alias $printprefix$method '$me$easyargs$quotedargs $method$aliasargs$easycurloptsargs$args';
EOF
			    done
			else
			    for method in $print_methods
			    do
				cat <<EOF
$printprefix$method () {
    $me$easyargs$quotedargs $method "\$@"$args$easycurloptsargs
};
EOF
			    done
			fi
		    fi
		    ;;
	    esac
	done

	exit 0
    fi

#

    if [ -z "$method" ]
    then
	test $# -ge 1 || usage 1
	method=$1
	shift
    fi

    if echo " $easy_methods " | fgrep -q " $method "
    then
	if [ -n "$assumecmdname" ]
	then
	    me=$method
	fi
	
        # See if the resource path is actually a URI. If so, extract the
        # endpoint ans resource path from there and pass the computed resource
        # path for the call.

	case "`echo $1 | tr '[A-Z]' '[a-z]'`" in
	    http://*|https://*)
		EASYENDPOINT=`echo $1 | sed 's,^\([^/]*:///*[^/]*\).*,\1,'`
		resourcepath=`echo $1 | sed 's,^[^/]*:///*[^/]*\(.*\),\1,'`
		shift
		;;
	esac
	if [ -z "$EASYENDPOINT" ]
	then
	    >&2 echo $me: unable to determine an endpoint to call
	    exit 2
	fi
	
	call $method $resourcepath ${1+"$@"}
    else
	case "$method" in
	    -*)
		usage 1
		;;
	    *)
		>&2 echo $me: unknown method: $method
		exit 6
		;;
	esac
    fi
}

# Do a quick check for --no-env first...

for arg
do
    case "$arg" in
	--no-env)
	    noenv=1
	    ;;
        -*)
	    ;;
	*)
	    break
	    ;;
    esac
done

if [ -n "$noenv" ]
then
    unset EASYOPTS
    unset EASYCURLOPTS
fi

takeiteasy $EASYOPTS ${1+"$@"}

